name: Emscripten build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    paths:
      # This action only runs on push when C++ files are changed
      - "**.cpp"
      - "**.h"
      - "**.cmake"
      - "**Lists.txt"
      - "**-emscripten.yml"
  workflow_dispatch:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and deploy
    runs-on: macos-14

    steps:
      - name: Install dependencies
        run: |
          brew install ninja
          curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/9990c9ddd731e97581a3312ca0358b45b14d1cc6/Formula/e/emscripten.rb && brew install ./emscripten.rb

      - name: Check file_packager
        run: |
          if [ ! -f /opt/homebrew/Cellar/emscripten/4.0.9/libexec/tools/file_packager ]; then
            echo "file_packager missing, reinstalling emscripten"
            brew uninstall emscripten
            ls /opt/homebrew/Cellar/emscripten/4.0.9/libexec/tools/
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      # Setup caching of build artifacts to reduce total build time (only Linux and MacOS)
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: |
          emcmake cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel 4

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{github.workspace}}/build

      - name: Copy web app
        working-directory: ${{github.workspace}}/build
        run: |
          mkdir deploy
          cp Samplin\ Safari.data Samplin\ Safari.html Samplin\ Safari.js Samplin\ Safari.wasm SamplinSafari_favicon.png FileSaver.js deploy/
          mv deploy/Samplin\ Safari.html deploy/index.html

      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{github.workspace}}/build/deploy
