name: macOS build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    paths:
      # This action only runs on push when C++ files are changed
      - "**.cpp"
      - "**.h"
      - "**.cmake"
      - "**Lists.txt"
      - "**-mac.yml"
  workflow_dispatch:

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: ${{ matrix.config.name }} (${{ matrix.buildtype }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "macOS 11", os: macos-11 }
          - { name: "macOS 12", os: macos-12 }
        buildtype: [Release, Debug]

    steps:
      - name: Install dependencies
        run: brew install ninja create-dmg

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      # Setup caching of build artifacts to reduce total build time (only Linux and MacOS)
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.config.os }}-${{ matrix.buildtype }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build/${{ matrix.buildtype }} -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DCMAKE_POLICY_DEFAULT_CMP0135=NEW -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

      - name: Build
        run: cmake --build ${{github.workspace}}/build/${{ matrix.buildtype }} --parallel 4 --config ${{ matrix.buildtype }}

      - name: Checking that Samplin Safari runs
        run: |
          ${{github.workspace}}/build/${{ matrix.buildtype }}/Samplin\ Safari.app/Contents/MacOS/Samplin\ Safari --help

      - name: Creating dmg (macOS)
        if: runner.os == 'macOS'
        run: |
          RESULT="${{github.workspace}}/build/${{ matrix.buildtype }}/SamplinSafari.dmg"
          test -f $RESULT && rm $RESULT
          create-dmg --window-size 500 300 --icon-size 96 --volname "Samplin Safari Installer" --app-drop-link 360 105 --icon Samplin\ Safari.app 130 105 $RESULT ${{github.workspace}}/build/${{ matrix.buildtype }}/Samplin\ Safari.app

      - name: Archive dmg (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: SamplinSafari-${{ matrix.config.os }}-${{ matrix.buildtype }}.dmg
          path: |
            ${{github.workspace}}/build/${{ matrix.buildtype }}/SamplinSafari.dmg

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.config.os }}-${{ matrix.buildtype }}
          path: |
            ${{github.workspace}}/build/${{ matrix.buildtype }}
